import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3000',portal=process.env.PORTAL_URL||`${base}/portal-preview/index.html`;
const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||undefined,args:['--no-sandbox']});
const results=[],errors=[];await mkdir('docs/preview-evidence',{recursive:true});
async function check(name,fn,options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',...options}),p=await c.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push({name,error:e.message}));try{await fn(p);results.push({name,result:'pass'});}catch(e){results.push({name,result:'fail',detail:e.message});}finally{await c.close();}}
const shot=async(p,name)=>{const data=await p.screenshot({path:`docs/preview-evidence/content-${name}.jpg`,type:'jpeg',quality:55});console.log(`FF_CONTENT_SHOT_${name}=${data.toString('base64')}`);};
await check('The first screen explains the audience, offer, price and next action',async p=>{await p.goto(base);assert.match(await p.locator('.mk-hero-eyebrow').textContent(),/Custom websites for independent businesses/);assert.match(await p.locator('.mk-hero-copy .mk-body').textContent(),/custom website.*understand your business/);assert.match(await p.locator('.mk-included').textContent(),/A\$1,500.*3 revision rounds/);assert.equal(await p.locator('.mk-hero-actions a').first().getAttribute('href'),'/preview/start');await shot(p,'hero');});
await check('Guided portal tasks open the right surface without reloading a draft',async p=>{await p.goto(base);await p.locator('[data-preview-task="pages"]').click();const frame=p.frameLocator('#marketing-portal');await frame.locator('[data-view-panel="pages"]').waitFor({state:'visible'});await frame.locator('[data-field="heading"]').fill('A draft kept between tasks');await p.locator('[data-preview-task="analytics"]').click();await frame.locator('[data-view-panel="analytics"]').waitFor({state:'visible'});await p.locator('[data-preview-task="review"]').click();await frame.locator('[data-view-panel="review"]').waitFor({state:'visible'});await p.locator('[data-preview-task="pages"]').click();await frame.locator('[data-view-panel="pages"]').waitFor({state:'visible'});assert.equal(await frame.locator('[data-field="heading"]').inputValue(),'A draft kept between tasks');assert.equal(await p.locator('[data-preview-task="pages"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.mk-preview-caption a').getAttribute('href'),'/preview?view=pages');await p.locator('#portal').evaluate(e=>e.scrollIntoView({block:'start'}));await shot(p,'workspace');});
await check('Full previews preserve task context and reject unknown views',async p=>{await p.goto(base+'/preview?view=analytics');await p.frameLocator('.standalone-preview iframe').locator('[data-view-panel="analytics"]').waitFor({state:'visible'});await p.goto(base+'/preview?view=unknown');await p.frameLocator('.standalone-preview iframe').locator('[data-view-panel="review"]').waitFor({state:'visible'});});
await check('Review instructions explain each mode as the customer changes it',async p=>{await p.goto(portal);assert.match(await p.locator('.review-guide').textContent(),/Collect the changes.*whole round/);await p.locator('#modeBtn').click();await p.locator('[data-mode="Edit site"]').click();assert.match(await p.locator('.review-guide').textContent(),/Update words and images directly/);await p.locator('#modeBtn').click();await p.locator('[data-mode="Browse mode"]').click();assert.match(await p.locator('.review-guide').textContent(),/See the website as a visitor/);});
await check('Marketing and portal describe Core and Pro with the same capabilities and prices',async p=>{await p.goto(base);const core=await p.locator('.mk-price-secondary>div').first().textContent(),pro=await p.locator('.mk-price-secondary>div').last().textContent();for(const term of ['content updates','basic analytics','search details','domain management'])assert.ok(core.includes(term));assert.match(pro,/A\$39 \/ month/);for(const term of ['States','deeper analytics','search insights'])assert.ok(pro.includes(term));await p.goto(portal);await p.locator('#leftRail [data-view="billing"]').click();const billing=await p.locator('[data-view-panel="billing"]').textContent();for(const term of ['Content updates','basic analytics','search details','domain management','A$200','A$1,300','A$1,500','A$39 / month','A$150'])assert.ok(billing.includes(term),term);await p.locator('[data-ops="upgrade-pro"]').click();const dialog=await p.locator('#opsModal').textContent();for(const term of ['States','deeper analytics','search insights','A$39 / month'])assert.ok(dialog.includes(term));});
await check('New content remains readable without horizontal clipping at small widths',async p=>{await p.goto(base);for(const width of [320,390,768,1024]){await p.setViewportSize({width,height:900});for(const selector of ['.mk-hero-copy','.mk-outcomes','.mk-work-context','.mk-preview-tasks','.mk-price-line','.mk-first','.mk-faq-grid']){const size=await p.locator(selector).evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.ok(size.scroll<=size.width+1,`${selector} clips at ${width}: ${size.scroll}/${size.width}`);}}await p.setViewportSize({width:390,height:844});await p.locator('#pricing').evaluate(e=>e.scrollIntoView({block:'start'}));await shot(p,'phone-pricing');});
await check('Rendered marketing and portal surfaces use no em dashes',async p=>{await p.goto(base);assert.ok(!(await p.locator('body').innerText()).includes('\u2014'));assert.ok(!(await p.title()).includes('\u2014'));await p.goto(portal);for(const view of ['overview','direction','build','review','pages','analytics','seo','domains','connections','states','billing','launch','settings']){await p.evaluate(view=>showView(view),view);assert.ok(!(await p.locator('.view.active').innerText()).includes('\u2014'),view);}});
await writeFile('docs/preview-evidence/content-results.json',JSON.stringify({results,uncaughtErrors:errors},null,2));console.log(JSON.stringify({results,uncaughtErrors:errors},null,2));await browser.close();if(results.some(r=>r.result==='fail')||errors.length)process.exitCode=1;
