import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3003';
const portal=process.env.PORTAL_URL||'http://127.0.0.1:4174';
const browser=await chromium.launch({executablePath:process.env.TEST_CHROME,args:['--no-sandbox']});
const results=[],errors=[];
async function check(name,fn){const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));try{await fn(page);results.push({name,result:'pass'})}catch(e){results.push({name,result:'fail',detail:e.message})}finally{await context.close()}}
await check('Password visibility preserves the typed value',async p=>{await p.goto(base+'/preview/start');await p.getByLabel('Password',{exact:true}).fill('preview-example');await p.getByRole('button',{name:'Show password'}).click();assert.equal(await p.getByLabel('Password',{exact:true}).getAttribute('type'),'text');assert.equal(await p.getByLabel('Password',{exact:true}).inputValue(),'preview-example');await p.getByRole('button',{name:'Hide password'}).click();assert.equal(await p.getByLabel('Password',{exact:true}).getAttribute('type'),'password')});
await check('Malformed saved onboarding selections recover safely',async p=>{await p.goto(base);await p.evaluate(()=>localStorage.setItem('ff-preview-onboarding-v1',JSON.stringify({name:'Mori House',description:'A restaurant.',goals:null,feels:42})));await p.goto(base+'/preview/start');await p.getByRole('button',{name:'Continue with Google'}).click();assert.equal(await p.getByRole('textbox',{name:'Business name',exact:true}).inputValue(),'Mori House');assert.equal(await p.locator('.obp-chips button[aria-pressed="true"]').count(),0)});
await check('SEO counters update and describe their inputs',async p=>{await p.goto(portal);await p.locator('#leftRail [data-view="seo"]').click();await p.locator('[data-field="seoTitle"]').fill('A'.repeat(70));assert.equal(await p.locator('[data-field="seoTitle"]').getAttribute('aria-describedby'),'detail-seoTitle');assert.match(await p.locator('#detail-seoTitle').textContent(),/70 \/ 65/);assert.ok(await p.locator('#detail-seoTitle').evaluate(e=>e.classList.contains('warning')))});
await check('Save shortcut retains a verified device copy',async p=>{await p.goto(portal);await p.keyboard.press('Control+s');assert.match(await p.locator('#saveState').textContent(),/Saved/);assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('fourthform-mori-local-v5')).savedAt))});
await check('Mobile drawers expose state and restore focus on Escape',async p=>{await p.setViewportSize({width:390,height:900});await p.goto(portal);await p.locator('#mobileMenu').click();assert.equal(await p.locator('#mobileMenu').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.locator('#mobileMenu').getAttribute('aria-expanded'),'false');assert.ok(await p.locator('#mobileMenu').evaluate(e=>e===document.activeElement));await p.screenshot({path:'docs/preview-evidence/details-phone.png'})});
await check('Editing a checked domain invalidates its status',async p=>{await p.goto(portal);await p.locator('#leftRail [data-view="domains"]').click();await p.locator('[data-field="domain"]').fill('  MORIHOUSE.COM.AU  ');await p.locator('[data-ops="check-domain"]').click();assert.equal(await p.locator('[data-field="domain"]').inputValue(),'morihouse.com.au');await p.locator('[data-field="domain"]').fill('another.example');assert.equal(await p.locator('[data-domain-status]').textContent(),'Needs verification')});
await check('DNS copy gives a fallback when clipboard is unavailable',async p=>{await p.goto(portal);await p.locator('#leftRail [data-view="domains"]').click();await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true}));await p.locator('[data-ops="copy-dns"]').click();assert.match(await p.locator('#toast').textContent(),/CNAME www/)});
await mkdir('docs/preview-evidence',{recursive:true});await writeFile('docs/preview-evidence/details-results.json',JSON.stringify({results,uncaughtErrors:errors},null,2));console.log(JSON.stringify({results,uncaughtErrors:errors},null,2));await browser.close();if(results.some(r=>r.result==='fail')||errors.length)process.exitCode=1;
